language: ruby
rvm:
 - 2.5.3

dist: xenial

services:
  - neo4j
  - postgresql

addons:
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - wget -O - https://debian.neo4j.com/neotechnology.gpg.key | sudo apt-key add -
  - echo 'deb https://debian.neo4j.com stable 3.5' | sudo tee /etc/apt/sources.list.d/neo4j.list
  - sudo apt-get update
  - sudo apt-get install neo4j
  - yarn install
  - cp config/neo4j.yml.travis config/neo4j.yml
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres

script:
  - bundle exec rails db:schema:load RAILS_ENV=test
  - bundle exec rspec
