version: '3'
services:
  rails_app:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - pg_db
      - neo4j_db

  pg_db:
    image: postgres:10.4
    volumes:
      - ./tmp/db/postgresql:/var/lib/postgresql/data

  neo4j_db:
    image: neo4j:3.4
    volumes:
      - ./tmp/db/neo4j/dev/data:/data
      - ./tmp/db/neo4j/dev/logs:/logs
    environment:
      - NEO4J_AUTH=none
    ports:
      - '7474:7474'

  neo4j_db_test:
    image: neo4j:3.4
    volumes:
      - ./tmp/db/neo4j/test/data:/data
      - ./tmp/db/neo4j/test/logs:/logs
    environment:
      - NEO4J_AUTH=none
    ports:
      - '7475:7474'
