version: '3'
services:
  rails_app:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - pg_db
      - neo4j_db
  pg_db:
    image: postgres
    volumes:
      - ./tmp/db/postgresql:/var/lib/postgresql/data
  neo4j_db:
    environment:
      - NEO4J_AUTH=none
    image: neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - ./tmp/db/neo4j/data:/data
