development:
  type: http
  url: <%= ENV['GRAPHENEDB_URL'] || ENV['NEO4J_URL'] || 'http://localhost:7474' %>

test:
  type: http
  url: <%= ENV['NEO4J_TEST_URL'] || 'http://localhost:7474' %>

production:
  type: http
  url: <%= ENV['GRAPHENEDB_URL'] || ENV['NEO4J_URL'] || 'http://localhost:7474' %>
