development:
  type: http
  url: <%= "http://#{ ENV.fetch('NEO4J_HOST', 'localhost') }:7474" %>

test:
  type: http
  url: http://neo4j_db_test:7474

production:
  type: http
  url: <%= ENV['GRAPHENEDB_URL'] %>
